# -------------------------------
# DATABASE CONFIG (SPRING BOOT)
# -------------------------------
spring.datasource.url=jdbc:h2:mem:quantitydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# -------------------------------
# H2 CONSOLE
# -------------------------------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# -------------------------------
# GOOGLE OAUTH2
# -------------------------------
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#${GOOGLE_CLIENT_ID}
#this will give error go and check the id and password of google client annd do it manually 
#you can get it from systemenv too by System.systemenvread more*/
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google